### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by jaythegeek** [shivanshtalwar0/flutter_janus_client#2]
Hey, so great work on getting this far. I'm having a bit of trouble getting the project going or importing it in to a new one. I am on flutter master channel. 

What's curious, I can see you are running it on Android. So I install.the app. Give the permissions manually to the camera and mic from the app settings. And then hit the call button. Nothing happens. 

When I run it from iOS. I get a websocket connection. Can see the session /.IDs all created. But the app crashes.

So just wondering if I'm doing something specifically wrong. My server is already setup and running electron / browser peers via Websockets / HTTPS API

I'd like to help or fork from this project. So any insight would be awesome. 

Thanks
Jay

**Comment by shivanshtalwar0** [comment]
About ios its probably permission related issue or maybe something specific to ios part of flutter webrtc i just can't comment on that without trying since i don't own an ios device its really not possible for me to test what's going wrong, about android, in my experience when you trying to connect to your janus instance most of the times no connectivity occurs due to ice candidates error so make sure your turn and stun server are specified in your janus config file also you might think passing stun and turn in configuration will suffice but that's not really the case janus need turn and stun server on both client side aswell as server side.
With That being said it should work normally

**Comment by shivanshtalwar0** [comment]
You could try docker image that i have created to save yourself from compilation.
[Janusgateway](https://hub.docker.com/r/shivanshtalwar0/janusgateway)
Closing this issue for now, you can reopen if it still doesn't work
