### ISSUE TITLE
Unified Plan

### ISSUE THREAD

**Issue by igala** [shivanshtalwar0/flutter_janus_client#8]
Great project!!

Are you planning to support unified plan?

**Comment by shivanshtalwar0** [comment]
Definitely! Its on my todo list, once audioroom support and testing is done i will develop it

**Comment by igala** [comment]
I am considering adding the support for unified plan to the project. What do you think should be the changes in order to be aligned with the project architecture?

**Comment by igala** [comment]
I am considering helping in implementing the unified plan support. Will it work for you? Can you give some guidelines?

**Comment by shivanshtalwar0** [comment]
Sure I would love to have a contribution from a lovely community!
Regarding guidelines for unified support
(1) First of all  we need to verify what is the status of flutter_webrtc when it comes to unified plan because ultimately all webRTC stack depends on flutter_webrtc plugin
(2) We need to make a separate branch for unified/multistreaming support, as Janus gateway now supports multistreaming for quite a while now on the multistreaming branch
(3) we need to heavily rely on Janus multistreaming branch for implementation and examples for the same
once we have working examples for unified support on a unified branch we will then focus on integrating it with the current codebase that is master

do share your views on how you feel about this plan?

**Comment by shivanshtalwar0** [comment]
According to this unified plan is under development
[unified plan webrtc](https://github.com/flutter-webrtc/flutter-webrtc/issues/99)

**Comment by shivanshtalwar0** [comment]
for the time being, you could help me complete the audio room and testing of this project.
Thanks for your interest!

**Comment by igala** [comment]
Hi,

1. Unified plan is supported in flutter webrtc, you can check the main page of the repo, please look at the table:
https://github.com/flutter-webrtc/flutter-webrtc

Also the unified plan branch was merged in the the master 

2. Yes I will work on a new branch for this change since Janus do not support both plans they transitioned to unified plan only.

3. Yes I agree , it will be relied on the Janus JS client . Your code is not organized on the same principles as the Janus JS. I will try to fit this in, any guideline you prefer I follow?

I think working on the unified plan transition will your package much more useful since it is an infrastructure improvement.

**Comment by shivanshtalwar0** [comment]
Yes organization is different since janus js needs to support multiple browsers but working principle is same and i agree unified support is much needed for project like this just follow along same janusjs examples for each plugin in order to develop multistreaming support in case of any doubt feel free to reach out to me at shivanshtalwar0@gmail.com

**Comment by shivanshtalwar0** [comment]
For development purpose you could use 
Rest Multistream https://janus.onemandev.tech/mjanus
Websocket Multistream
https://janus.onemandev.tech/mjanus/websocket
