### ISSUE TITLE
is there flutter sdk for janus?

### ISSUE THREAD

**Issue by feedbate** [shivanshtalwar0/flutter_janus_client#9]
i am trying to deploy own janus SFU for flutter video conference app.... i want to use my own plugin instead of janus_client flutter plugin by building own fluter sdk.. so is there any reference of flutter sdk for janus?

**Comment by shivanshtalwar0** [comment]
As of now there are no standard ask for flutter Janus but if you really want to build your own SDK/plugin kindly refer Janus documentation and for example consider flutter Janus client ,also you could contribute your code to flutter Janus client in order to make it production ready by testing and proposing new ideas and features
